### ISSUE TITLE
7s toggle needs to stay on

### ISSUE THREAD

**Issue by grjanke** [matttrenary/rugby-ratings#18]
When we switch between Rankings / Results pages, the display needs to remain on "7s" if that's where it was before the switch.

**Comment by grjanke** [comment]
`<script>if (window.location.hash.includes('#7s')) {$('#results7s-tab').tab('show'); $('#rankings7s-tab').tab('show')}</script>`

Adding the above line to the bottom of all pages with 15s/7s tabs, and appending `#7s` to every link inside a 7s tab, will solve this issue.

**Comment by grjanke** [comment]
Just committed the above changes. This issue should be completely solved! Waiting to close this pending @matttrenary review.

Two things:
- The Results/Rankings navbar links still default to 15s no matter what. My assessment is that there's no reasonable expectation to see 7s when clicking those links (as opposed to clicking team page links on a 7s results/rankings page).
- My solution involves an extra JS script running on every base_template page. I'm slightly worried that there's a little bit of extra lag time now, but I might just be paranoid.

**Comment by matttrenary** [comment]
Awesome work!

- I agree that Results/Rankings should still be defaulted to 15
- Yeah I think the tiny bit of lag is because after clicking on a new team it's a two step process to show the 7s. First the page loads with 15s showing as default, then the 7s tab is shown. (You don't experience this lag with clicking team to team within 15s because there's no tab swapping.)
- It's really only lag from the tab swap. You can see the same lag when swapping 15s/7s tabs for a single team.
- I'm thinking this is actually a built in UX "feature" within bootstrap, and that if this "feature" didn't exist we wouldn't really experience any lag. It's not like there's actually any data being loaded. It's just a bit of text that's being hidden/displayed.

So:
- This is obviously way better than before! Great job.
- If we really wanted to eliminate this, we'd need to override something in bootstrap.
- Or we figure out a different tab swapping mechanism that falls outside of bootstrap. Probably doesn't exist.
- Or we figure out how to actually load the page with 7s as default, which isn't really possible since the 15s default is written into the page html. We'd have to create two separate pages for an individual team and that seems less desirable.

But overall, we probably just move on to more important things since this has gotten us like 99% of the way there.

Separately, I do have a question about why the code accounts for both #results7s-tab and #rankings7s-tab. Seems like we could restrict the code to whichever page we were using it on (results or rankings). Though this probably doesn't impact performance.

**Comment by grjanke** [comment]
Methods for us to consider later (outside the scope of this issue) in order to fix page lag:
- Override Bootstrap to remove any delay with tab switching
- Separate 15s and 7s into different HTML pages (can still keep the tab aesthetic)

**Comment by grjanke** [comment]
@matttrenary regarding your question on why the code accounts for both #results7s-tab and #rankings7s-tab:
- Just flexibility for us. It would take more work now and later to specify the tab-type on each page.
- Any impact on performance is a lot more minimal than the tab-switching lag (which is already minimal).
- Perhaps the simplest option is to combine #results7s-tab and #rankings7s-tab into one #7s-tab id, since I don't believe we ever use them at the same time. But that sort of code cleaning seems like a low priority and isn't necessarily preferable.

Thoughts? Feel free to close this issue at any point if satisfied.

**Comment by matttrenary** [comment]
Closing. Onward and upward!
