### ISSUE TITLE
Update UX in prep for results on frontpage

### ISSUE THREAD

**Issue by matttrenary** [matttrenary/rugby-ratings#35]
- Remove "RugbyHawk" title and subtitle on frontpage
- Add subtitle text to the About page
- Adjust .table dh and .table th css for padding to .2rem instead of .75rem. (This will tighten up rows across the entire site.)
- Remove Results from the menu, and put a link to the Results page at the bottom of the recent results div on the front page
- Move the score submission form to it's own page. Discuss where we'll display links to this page.

@grjanke would like to hear your thoughts on these.

**Comment by grjanke** [comment]
- **Remove RugbyHawk title/subtitle:** I agree; popular websites just keep their title in the top left (like we already do)
- **Add subtitle text to the About page:** I agree
- **Adjust .table dh and .table th css for padding:** Unsure about this one; I initially think that .75 looks better, but my opinion isn't set in stone.
- **Remove Results from the menu:** Tentatively disagree with removing Results from the menu, since the menu just isn't messy enough yet. Agree about adding another way to view results on the home page.
- **Move the score submission form to it's own page:** If score submission page were to move to the top menu, then I wouldn't mind having it replace the Results page.

**Comment by matttrenary** [comment]
Implemented first two bullets.

Kicking the can on the remaining three until we can all view them on the front page that has a table of results/games.

**Comment by matttrenary** [comment]
@grjanke 
Now that we have the table on the front page, what do we think about the remaining 3 items?
- dh and th padding. Implemented for front page but not results page. (image below as example on front page)
- Removing Results from menu
- Moving score submission to its own page

![image](https://github.com/user-attachments/assets/cd65cd5f-66f1-4c45-9d12-0e74f0748836)

**Comment by matttrenary** [comment]
Any further menu/UX will be a separate issue.
